# Generated by Django 4.1.2 on 2022-10-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_is_adm_alter_user_department_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_adm",
            field=models.BooleanField(default=False),
        ),
    ]
