# Generated by Django 4.1.2 on 2022-11-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_department_id_user_department"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="department",
            new_name="support_department",
        ),
    ]
