# Generated by Django 4.1.2 on 2022-10-31 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_adm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_adm",
        ),
    ]
