# Generated by Django 4.1.2 on 2022-10-31 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="ticket_id",
            new_name="ticket",
        ),
    ]
