# Generated by Django 4.1.2 on 2022-10-31 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("solutions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="solution",
            old_name="ticket_id",
            new_name="ticket",
        ),
        migrations.RenameField(
            model_name="solution",
            old_name="user_id",
            new_name="user",
        ),
    ]
