# Generated by Django 4.1.2 on 2022-10-31 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_remove_ticket_solution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("solutions", "0002_rename_ticket_id_solution_ticket_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solution",
            name="ticket",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="tickets.ticket"
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
