# Generated by Django 4.1.2 on 2022-11-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("solutions", "0005_alter_solution_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solution",
            name="time_taken",
        ),
    ]
