# Generated by Django 4.1.2 on 2022-11-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("solutions", "0006_remove_solution_time_taken"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="solution",
            options={"ordering": ["id"]},
        ),
    ]
