# Generated by Django 4.1.2 on 2022-11-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("solutions", "0007_alter_solution_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="solution",
            old_name="user",
            new_name="solver",
        ),
    ]
