# Generated by Django 4.1.2 on 2022-10-31 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="department_id",
            new_name="department",
        ),
    ]
