# Generated by Django 4.1.2 on 2022-10-31 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_rename_department_id_ticket_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="solution",
        ),
    ]
