# Generated by Django 4.1.2 on 2022-11-01 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tickets", "0004_remove_ticket_solution"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="department",
            new_name="support_department",
        ),
        migrations.AddField(
            model_name="ticket",
            name="support",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supported_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
