# Generated by Django 4.1.2 on 2022-11-03 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_rename_department_ticket_support_department_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["id"]},
        ),
    ]
