# Generated by Django 4.1.2 on 2022-11-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_alter_ticket_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="support",
            new_name="support_user",
        ),
    ]
