# Generated by Django 4.1.2 on 2022-11-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_rename_support_ticket_support_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="user",
            new_name="owner",
        ),
    ]
